spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
      continue-on-error: true
      encoding: utf-8
  jpa:
    database: h2
    show-sql: true
  h2:
    console:
      enabled: true